parameters:
#    xiod_backend.example.class: Xiod\Bundle\BackendBundle\Example

services:
#    xiod_backend.example:
#        class: %xiod_backend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
