parameters:
#    xiod_frontend.example.class: Xiod\Bundle\FrontendBundle\Example

services:
#    xiod_frontend.example:
#        class: %xiod_frontend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
