xiod_admin_generator_homepage:
    pattern:  /
    defaults: { _controller: XiodAdminGeneratorBundle:Default:index }


xiod_admin_generator_manage_routing:
    pattern:  /routing/
    defaults: { _controller: XiodAdminGeneratorBundle:Routing:index }

xiod_admin_generator_manage_entities:
    pattern:  /entities/
    defaults: { _controller: XiodAdminGeneratorBundle:Entities:index }
