parameters:
#    xiod_admin_generator.example.class: Xiod\Bundle\AdminGeneratorBundle\Example

services:
#    xiod_admin_generator.example:
#        class: %xiod_admin_generator.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
