parameters:
    xiod_admin_generator.menu.class: Xiod\Bundle\AdminGeneratorBundle\Menu\MenuBuilder

services:
    xiod_admin_generator.menu_builder:
        class: %xiod_admin_generator.menu.class%
        arguments: ["@knp_menu.factory"]

    xiod_admin_generator.menu.main:
        class: Knp\Menu\MenuItem
        factory_service: xiod_admin_generator.menu_builder
        factory_method: createGeneratorMainMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: generator.menu.main }
